

[database]
host     = "sql12.freesqldatabase.com"
user     = "sql12832187"
password ="uqiTbrAxvR"
name     =  "sql12832187"

[email]
sender_email = "oquiz92@gmail.com"
app_password ="vjvyzsbisynlcaij"
