DB_HOST     = "sql12.freesqldatabase.com"
DB_USER     = "sql12832187"
DB_PASSWORD = "uqiTbrAxvR"
DB_NAME     =  "sql12832187"

SENDER_EMAIL        ="oquiz92@gmail.com"
SENDER_APP_PASSWORD = "vjvyzsbisynlcaij"

SPECIAL_CHARS = "!@#$%^&*()_+-=[]{}|;':\",./<>?"───────────────────────────────────────────────────────────────
