

[database]
host     = "sql12.freesqldatabase.com"
user     = "sql12832867"
password ="rzZpwssbMK"
name     =  "sql12832867"

[email]
sender_email = "charitha20060112@gmail.com"
app_password ="vjvyzsbisynlcaij"
